# Redirect to keep very old URL alive
[[redirects]]
  from = "/gfx/"
  to = "/art/"

# Preserve some wonky, old URLs
[[redirects]]
  from = "/blog/2021/07/15/a-@font-face-anti-pattern/"
  to = "/blog/2021/07/15/font-face-anti-pattern/"
